import mongoose from 'mongoose';
const {Schema,model}=mongoose;
const oid=Schema.Types.ObjectId;
const options={timestamps:true};
export const Restaurant=model('Restaurant',new Schema({name:{type:String,required:true},active:{type:Boolean,default:true}},options));
export const Outlet=model('Outlet',new Schema({restaurantId:{type:oid,required:true},name:String,address:String,phone:String,areas:[String],active:{type:Boolean,default:true},deliveryEnabled:{type:Boolean,default:false},deliveryFee:{type:Number,default:3000},pickupEnabled:{type:Boolean,default:true},opening:{type:String,default:'11:00'},closing:{type:String,default:'23:00'},leadMinutes:{type:Number,default:30},slotCapacity:{type:Number,default:15},cancellationPercent:{type:Number,default:10},orderSeq:{type:Number,default:0}},options));
export const User=model('User',new Schema({email:{type:String,required:true,unique:true},name:String,passwordHash:{type:String,required:true,select:false},role:{type:String,enum:['super_admin','admin'],required:true},outletId:oid,active:{type:Boolean,default:true}},options));
const sessionSchema=new Schema({tokenHash:{type:String,unique:true},userId:oid,expiresAt:Date},options);sessionSchema.index({expiresAt:1},{expireAfterSeconds:0});export const Session=model('Session',sessionSchema);
export const Ingredient=model('Ingredient',new Schema({outletId:{type:oid,required:true,index:true},name:String,unit:String,stock:{type:Number,min:0,default:0},reserved:{type:Number,min:0,default:0},consumed:{type:Number,min:0,default:0},wasted:{type:Number,min:0,default:0},lowAt:{type:Number,min:0,default:2}},options));
export const MenuItem=model('MenuItem',new Schema({outletId:{type:oid,required:true,index:true},name:String,description:String,category:String,price:{type:Number,min:100},available:{type:Boolean,default:true},veg:{type:Boolean,default:false},serves:String,tag:String,image:{type:String,default:'/food.jpg'},recipe:[{ingredientId:{type:oid,required:true},quantity:{type:Number,min:0.001,required:true},_id:false}]},options));
const slotSchema=new Schema({outletId:oid,time:Date,count:{type:Number,default:0}},options);slotSchema.index({outletId:1,time:1},{unique:true});export const Slot=model('Slot',slotSchema);
const orderSchema=new Schema({number:String,idempotencyKey:{type:String,unique:true},tokenHash:{type:String,select:false},outletId:{type:oid,index:true},name:String,mobile:String,address:String,area:String,fulfilment:{type:String,enum:['pickup','delivery','dine_in']},source:{type:String,default:'online'},tableId:oid,tableName:String,scheduledAt:Date,items:[{itemId:oid,name:String,quantity:Number,unitPrice:Number,_id:false}],requirements:[{ingredientId:oid,quantity:Number,_id:false}],subtotal:Number,deliveryFee:Number,total:Number,cancellationPercent:Number,status:{type:String,default:'pending_payment',index:true},paymentStatus:{type:String,default:'pending'},paymentId:String,razorpayOrderId:{type:String,index:true},confirmedAt:Date,expiresAt:Date,inventoryState:{type:String,enum:['reserved','consumed','released'],default:'reserved'},slotReleased:{type:Boolean,default:false},cancellationFee:Number,refundAmount:Number,refundStatus:{type:String,default:'none'},refundId:String,refundClaimedAt:Date,refundError:String,cancelledAt:Date,history:[{status:String,at:Date,_id:false}],preview:{type:Boolean,default:false}},options);orderSchema.index({outletId:1,createdAt:-1});orderSchema.index({outletId:1,number:1},{unique:true});export const Order=model('Order',orderSchema);
export const StockMovement=model('StockMovement',new Schema({outletId:{type:oid,index:true},ingredientId:oid,orderId:oid,type:{type:String,enum:['purchase','adjustment','wastage','consumption']},quantity:Number,note:String,actor:String},options));

export const DiningTable=model('DiningTable',new Schema({outletId:{type:oid,required:true,index:true},name:{type:String,required:true},token:{type:String,required:true,unique:true},active:{type:Boolean,default:true},clearedAt:Date},options));
