import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const bytes=readFileSync(new URL('../public/models/redhandi-restaurant.glb',import.meta.url));
const jsonLength=bytes.readUInt32LE(12),gltf=JSON.parse(bytes.subarray(20,20+jsonLength)),binary=bytes.subarray(28+jsonLength);
function accessor(index){const a=gltf.accessors[index],v=gltf.bufferViews[a.bufferView],components={SCALAR:1,VEC3:3,VEC4:4}[a.type];assert.equal(a.componentType,5126);return Array.from({length:a.count},(_,i)=>Array.from({length:components},(_,j)=>binary.readFloatLE((v.byteOffset||0)+(a.byteOffset||0)+i*(v.byteStride||components*4)+j*4)))}
function channel(node,path){for(const clip of gltf.animations){const c=clip.channels.find(c=>gltf.nodes[c.target.node].name===node&&c.target.path===path);if(c){const s=clip.samplers[c.sampler];return{times:accessor(s.input).flat(),values:accessor(s.output)}}}throw new Error('Missing animation: '+node+' '+path)}
test('Blender model contains animated host, chef, embedded branding and a printable ticket surface',()=>{assert.equal(bytes.readUInt32LE(0),0x46546c67);for(const name of ['Host','Chef','TicketFace','OrderSlip'])assert.ok(gltf.nodes.some(n=>n.name===name),name);assert.ok(gltf.images.some(i=>i.bufferView!==undefined));assert.ok(bytes.length<8*1024*1024,'Keep mobile asset below 8 MB');channel('Host_left_elbow','rotation');channel('Chef_right_shoulder','rotation')});
test('the host approaches the customer, settles, then returns to the kitchen after ordering',()=>{const {times,values}=channel('Host','translation');const at=t=>values[times.findIndex(time=>time>=t)];const start=at(0),arrived=at(3.7),waiting=at(7.5),delivered=values.at(-1);assert.ok(arrived[2]>start[2]+1.8,'approach moves toward the customer');assert.ok(Math.abs(waiting[2]-arrived[2])<.001,'attentive loop stays at the table');assert.ok(delivered[2]<arrived[2]-1.8,'delivery returns to the kitchen');assert.ok(times.at(-1)>=15.9)});
test('the order slip is hidden in welcome and appears only in the delivery segment',()=>{const {times,values}=channel('OrderSlip','scale');for(let i=0;i<times.length;i++){if(times[i]<7.8)assert.ok(values[i][0]<.01);if(times[i]>8.1)assert.ok(values[i][0]>.99)}});
