import {Dialog as D,AlertDialog as A,Select as S,Switch as W,Tabs as T,Checkbox as C} from 'radix-ui';
import {X,ChevronDown,Check} from 'lucide-react';
export function Dialog({open,onOpenChange,title,description,children,wide=false}){return <D.Root open={open} onOpenChange={onOpenChange}><D.Portal><D.Overlay className='modal-overlay'/><D.Content className={'modal-content '+(wide?'wide':'')}><D.Title className='modal-title'>{title}</D.Title>{description&&<D.Description className='modal-description'>{description}</D.Description>}<D.Close className='close-button' aria-label='Close'><X size={21}/></D.Close>{children}</D.Content></D.Portal></D.Root>}
export function Sheet({open,onOpenChange,title,description,children}){return <D.Root open={open} onOpenChange={onOpenChange}><D.Portal><D.Overlay className='modal-overlay'/><D.Content className='sheet-content'><D.Title className='modal-title'>{title}</D.Title><D.Description className='modal-description'>{description}</D.Description><D.Close className='close-button' aria-label='Close bag'><X size={22}/></D.Close>{children}</D.Content></D.Portal></D.Root>}
export function Confirm({open,onOpenChange,title,description,children,onConfirm,busy,confirmLabel='Confirm'}){return <A.Root open={open} onOpenChange={onOpenChange}><A.Portal><A.Overlay className='modal-overlay'/><A.Content className='modal-content'><A.Title className='modal-title'>{title}</A.Title><A.Description className='modal-description'>{description}</A.Description>{children}<div className='form-actions'><A.Cancel className='button outline' disabled={busy}>Keep order</A.Cancel><button className='button red' disabled={busy} onClick={onConfirm}>{busy?'Please wait…':confirmLabel}</button></div></A.Content></A.Portal></A.Root>}
export function Select({value,onValueChange,options,placeholder='Choose',label,disabled=false}){return <S.Root value={value||undefined} onValueChange={onValueChange} disabled={disabled}><S.Trigger className='select-trigger' aria-label={label||placeholder}><S.Value placeholder={placeholder}/><S.Icon><ChevronDown size={16}/></S.Icon></S.Trigger><S.Portal><S.Content className='select-content' position='popper' sideOffset={5}><S.Viewport>{options.map(o=><S.Item className='select-item' key={typeof o==='string'?o:o.value} value={typeof o==='string'?o:o.value}><S.ItemText>{typeof o==='string'?o:o.label}</S.ItemText><S.ItemIndicator><Check size={15}/></S.ItemIndicator></S.Item>)}</S.Viewport></S.Content></S.Portal></S.Root>}
export function Toggle({checked,onCheckedChange,label,disabled}){return <W.Root className='toggle' checked={checked} onCheckedChange={onCheckedChange} aria-label={label} disabled={disabled}><W.Thumb className='toggle-thumb'/></W.Root>}
export function Checkbox({checked,onCheckedChange,label}){return <label className='checkbox-label'><C.Root checked={checked} onCheckedChange={onCheckedChange} className='checkbox'><C.Indicator><Check size={13}/></C.Indicator></C.Root><span>{label}</span></label>}
export function Tabs({value,onValueChange,items}){return <T.Root value={value} onValueChange={onValueChange}><T.List className='category-row' aria-label='Menu category'>{items.map(item=><T.Trigger className={value===item?'active':''} key={item} value={item}>{item}</T.Trigger>)}</T.List></T.Root>}
export function Field({label,children,hint,...props}){return <label className='field'><span>{label}</span>{children||<input {...props}/>} {hint&&<small>{hint}</small>}</label>}
